agent_1:
  role: Researcher
  goal: Pesquisar o preço do Playstation 5 em 2026
  backstory: Encontrar o preço atualizado do Playstation 5 para o ano de 2026
  tools:
  - web_search
  - save_local_file
