task_1:
  description: Pesquisar o preço do Playstation 5 em 2026 utilizando a ferramenta
    web_search
  expected_output: Preço atualizado do Playstation 5 em 2026
  agent: agent_1
  output_file: output/preco_playstation_5_2026.json
